export interface Article {
  id: string;
  series: string;
  seriesColor: string;
  title: string;
  date: string;
  published: boolean;
  excerpt: string;
  content: string[];
}

export const articles: Article[] = [
  {
    id: 'coachiq-01',
    series: 'CoachIQ',
    seriesColor: 'var(--color-accent)',
    title: 'The Idea That Wouldn\'t Let Me Sleep',
    date: '2026-05-10',
    published: true,
    excerpt: 'It started with a conversation that went nowhere.',
    content: [
      'It started with a conversation that went nowhere.',
      'I had spent the better part of six months building something I believed in — a basketball knowledge system backed by two decades of coaching and data from professional leagues across three continents. Not opinions. Measurements. Points per possession. Shot quality by location and defender distance. Which defensive systems actually hold up when the game is on the line and which ones look good on a whiteboard and fall apart in the fourth quarter.',
      'I tried to share it with the people who needed it most.',
      'The response was silence. Polite, institutional silence. The kind that tells you the idea was heard and immediately filed somewhere it would never be opened again.',
      'I went home and stared at the files. Hundreds of pages. Charts. Data tables. Drill progressions I had tested with real players in real gyms over twenty years. All of it sitting there, completely useless to the people it was built for.',
      'That\'s when the question arrived that I couldn\'t shake.',
      'What if the problem wasn\'t the content?',
      'Documents push. They demand attention. They require the reader to meet them halfway — to sit down, to focus, to care enough to work through complexity. Most people, most of the time, won\'t do that. Not because they\'re lazy. Because nobody ever made it easy enough.',
      'What if I could make it a conversation instead?',
      'Not a chatbot that knows basketball. Something that knows this player. Their history. Their patterns. What they worked on last Tuesday. Where they\'re improving and where they\'re stuck. Something that could take twenty years of methodology and make it feel like talking to a coach who had been watching you for months.',
      'I started building it on a Tuesday evening after work.',
      'By Thursday I had my first architectural decision — and my first major problem.',
      'What happens when you build a knowledge base for a machine that doesn\'t understand basketball the way a coach does? And what does "understanding" even mean when you\'re dealing with vectors and embeddings instead of neurons?',
    ],
  },
  {
    id: 'coachiq-02',
    series: 'CoachIQ',
    seriesColor: 'var(--color-accent)',
    title: 'The Machine That Forgot Everything',
    date: '2026-05-14',
    published: true,
    excerpt: 'The first version worked perfectly. That was the problem.',
    content: [
      'The first version worked perfectly.',
      'That was the problem.',
      'I had built what the industry calls a RAG system — a way of grounding an AI\'s responses in a specific knowledge base rather than the general internet. The concept is elegant: feed the system your documents, it indexes them by meaning rather than keywords, and when someone asks a question it retrieves the most relevant pieces and constructs an answer from them.',
      '590 chunks of content. 23 documents. Shot quality data. Drill progressions. Defensive system analysis. All of it indexed, searchable, retrievable in milliseconds.',
      'A test player typed: "I want to shoot like Curry."',
      'The system returned a technically flawless answer. Curry\'s training methodology. Catch-and-shoot mechanics. The role of leg drive in generating consistent arc. Three drill recommendations with efficiency data attached.',
      'I read it and felt a specific kind of disappointment — the kind you feel when something is right and completely wrong at the same time.',
      'No fourteen-year-old was going to finish reading that. And if they somehow did, they still wouldn\'t know what to do tomorrow morning in an empty gym.',
      'The knowledge was accurate. The coaching was absent.',
      'Real coaches don\'t start with information. They start with action. Give the player something to do. Watch what happens. Then talk. So I rebuilt the agent\'s judgment layer. Not its knowledge. Its judgment. What I changed, and how, I\'m keeping to myself — it\'s the part of this build I\'m most protective of.',
      'But the result was immediate. The agent stopped lecturing. It started coaching.',
      'Then I found the second problem. The agent had no memory.',
      'Every conversation started from zero. It knew basketball. It didn\'t know this player. Didn\'t know they\'d been working on their crossover for three weeks. Didn\'t know their catch-and-shoot percentage had been quietly dropping. Didn\'t know they had a tryout coming and were trying not to think about it.',
      'Without that, every answer was generic. Technically correct. Completely impersonal.',
      'And impersonal coaching doesn\'t work.',
      'How do you give an AI a memory that actually changes how it coaches — and what happens when you discover the memory has to know what time of day it is?',
    ],
  },
  {
    id: 'coachiq-03',
    series: 'CoachIQ',
    seriesColor: 'var(--color-accent)',
    title: 'The Ghost in the Data',
    date: '2026-05-22',
    published: true,
    excerpt: 'The profile had to build itself.',
    content: [
      'The profile had to build itself.',
      'Asking a player to fill out a form before they could talk to a coach was the wrong order. Nobody opens a coaching app to fill in fields. They open it because they want help with something specific, right now.',
      'So I built it the other way around.',
      'The player starts talking. The agent listens. When a player mentions their position, it writes to the database silently. When they say their age, same thing. When they describe a goal, it goes in. The player never sees a form. The profile builds itself as a side effect of a real conversation.',
      'Five layers emerged from building this — not designed upfront, discovered through what actually mattered when the agent tried to give useful answers.',
      'Identity: position, age, level, physical type. Changes rarely. Drives how the agent routes its responses.',
      'Status: health, current injuries. Changes session to session. Open by default because a player who tweaked their ankle yesterday needs a different session than the one who didn\'t.',
      'Goals: this month, this season, long term. Separate because a player preparing for tryouts next week needs different emphasis than the same player in the off-season.',
      'Game Map: skill ratings across every major area of the game. Built from three sources — the player\'s own self-assessment, the agent\'s observations after watching enough evidence across a session, and eventually a coach\'s direct rating. They don\'t always agree. The coach\'s rating wins, because a coach sees the player accurately. The player often doesn\'t.',
      'Track Record: every drill ever assigned. How it felt. What the agent concluded. When it happened — including what time of day.',
      'The time of day detail took a while to understand why it mattered. A player whose shooting numbers drop in evening sessions isn\'t necessarily broken — that may be biological variance, not a mechanical problem. The data has to be rich enough to tell the difference between a skill gap and a circadian pattern. Without the timestamp, that distinction is invisible.',
      'The profile was now real. The memory was working. But then I discovered a structural problem in the knowledge base that threatened to quietly undermine everything.',
      'Not with an error. With silence.',
      'When a database grows, what kills quality isn\'t bad content — it\'s invisible redundancy. And the failure is completely silent. No error is thrown. You just get worse answers and you don\'t know why.',
    ],
  },
  {
    id: 'coachiq-04',
    series: 'CoachIQ',
    seriesColor: 'var(--color-accent)',
    title: 'The Silent Failure',
    date: '2026-05-28',
    published: true,
    excerpt: 'Here is something nobody tells you about building a RAG system at scale. It can fail silently.',
    content: [
      'Here is something nobody tells you about building a RAG system at scale.',
      'It can fail silently.',
      'Not crash. Not throw an error. Not produce an obviously wrong answer. Just quietly return results that are slightly less relevant, slightly less complete, and the answers start drifting toward generic without you being able to point to exactly why.',
      'I discovered this the hard way.',
      'The knowledge base had grown to 37 files across 14 categories. I had processed fourteen source documents and converted them into searchable chunks. Then I ran a test query on a topic I knew the system should handle well.',
      'The answer was fine. Not wrong. Not impressive. The kind of answer that makes you uncertain whether the retrieval actually found the right material or whether the AI was filling gaps from general knowledge.',
      'I dug into what the vector database had returned. Two files covered overlapping territory, written from different source documents, indexed as separate vectors. When a query touched that territory, both competed for the limited retrieval slots. The system was spending half its context on two partial versions of the same knowledge instead of one complete version plus something genuinely different.',
      'The duplication was invisible from the outside. No error. No warning. Just noise where signal should have been.',
      'Fixing it required a specific operation I won\'t describe in detail — it involves how vectors are identified and what happens if you remove them in the wrong order. What I will say is that doing it incorrectly leaves orphaned data in the database that continues to influence retrieval indefinitely, silently, in ways you cannot easily trace.',
      'I built a tracking system after that. Every file, every source, every deliberate decision about what to include and what to leave out — documented so I can see, at a glance, what exists and where it came from.',
      'Then I found a completely different kind of problem.',
      'The agent told a player working on post footwork that it wasn\'t really a skill for guards.',
      'That is wrong as coaching. Position tells you where a player operates on the floor. It never tells you what they can learn. A guard who posts up needs drop step footwork. A big who pops to the elbow needs jab step reads. Footwork is universal.',
      'I traced it to one section of the prompt — one line that connected position to skill selection. Rewrote that section. Behavior fixed immediately. No code change, no database change. One wrong assumption, one correction.',
      'That diagnostic process — observe the bad answer, identify which of four layers caused it, fix only that layer, test the exact same scenario again — became the standard. The most common mistake was assuming it was a prompt problem when it was actually a retrieval problem. Fixing a retrieval problem in the prompt does nothing except make the next real prompt problem harder to find.',
      'The agent was becoming more accurate. More consistent. More specific.',
      'It still didn\'t have a name.',
      'What happens when you realize a player doesn\'t want to talk to a product — and the answer changes everything about how the agent presents itself?',
    ],
  },
  {
    id: 'coachiq-05',
    series: 'CoachIQ',
    seriesColor: 'var(--color-accent)',
    title: 'The Coach',
    date: '2026-06-04',
    published: true,
    excerpt: 'The agent needed a name. Not a product name. A coaching name.',
    content: [
      'The agent needed a name.',
      'Not a product name. Not "CoachIQ Assistant" or a branded AI persona. A coaching name. Because a player doesn\'t open an app to talk to a product. They open it because they want a coach. The relationship only works if the agent is a coach — not something that sounds like one.',
      'The name is Coach. That\'s it.',
      'One rule followed from the name: Coach never references where it learned something. It doesn\'t say "according to my knowledge base" or "based on what I\'ve been told" or "my notes show." Coaches know things. They don\'t cite. The moment Coach mentions a source, the coaching relationship ends and a software product begins. Players don\'t want to talk to software.',
      'That rule — simple on the surface — had a cascading effect on the prompt. Every place where the agent had been hedging, attributing, qualifying its knowledge had to be rewritten. Coach knows. Coach observes. Coach assesses. Coach is direct.',
      'It changed the answers immediately.',
      'Not the content of the answers. The confidence behind them. The same information delivered by something that knows versus something that retrieved feels different. Players respond to it differently. They push back more. They engage more. They come back.',
      'The build continues. Real players are testing it now. Every conversation produces data. The evaluator runs silently on every response, checking eight rules, storing every failure in Firebase. Two weeks of that data will tell me more about what to fix than six months of guessing.',
      'There is no ending yet. That\'s not a writing choice. The product is still being built. The profile is growing. The knowledge base has gaps that real users are revealing. The CourtIQ data layer — with its 176 tracked skills, its scouting reports, its immutable session history — hasn\'t been connected yet. When it is, Coach will know this specific player in a way that no generic AI ever could.',
      'That connection is the next thing I\'m building.',
      'Follow along. The next article will be about what happens when two years of player data meets an AI that finally knows how to read it.',
    ],
  },
  {
    id: 'coachiq-06',
    series: 'CoachIQ',
    seriesColor: 'var(--color-accent)',
    title: 'The Card That Lied',
    date: '2026-06-14',
    published: true,
    excerpt: 'The app was ready to take money.',
    content: [
      'The app was ready to take money.',
      'I know that moment. It feels different from every other moment in a build. The code is done. The logic is tested. You sit down, open the payment page you built, enter your own card, and press confirm.',
      'Declined.',
      'I checked the integration. Correct. I checked my card balance. Fine. I tried a different card.',
      'Declined.',
      'I called the card company. Nothing wrong on their end. I contacted the payment processor. Their logs showed the transaction arriving and being rejected before it reached them — somewhere upstream, in infrastructure neither of us owned.',
      'I spent two evenings tracing it.',
      'What I eventually found had nothing to do with anything I had written. Somewhere between the user pressing confirm and the money moving, a service I had never heard of was making a decision. Not about fraud. Not about the card. About geography. Israeli users were hitting a wall that existed before the transaction even started — invisible, automatic, and completely outside anyone\'s control.',
      'The processor I had chosen was legitimate. The integration was correct. The problem was deeper than both.',
      'I made one decision that night and didn\'t second-guess it.',
      'By the following week the payment system was running on different infrastructure. I tested it the same way — my own card, confirm, wait.',
      'Approved.',
      'There is a version of this where I feel angry about the weeks I lost. I don\'t. You find out where the walls are by walking into them. That\'s the only way.',
      'The money problem was solved. The next problem was quieter — and harder to find.',
    ],
  },
  {
    id: 'coachiq-07',
    series: 'CoachIQ',
    seriesColor: 'var(--color-accent)',
    title: 'The Number That Does Damage',
    date: '2026-06-18',
    published: false,
    excerpt: 'I found the bug before any real user did.',
    content: [
      'I found the bug before any real user did.',
      'That almost never happens. Usually something breaks in production, on a real person\'s screen, at the worst possible moment. This time I was deep in a testing session — running through the coach side of the app, checking that data was writing to the right places — when I noticed something move that shouldn\'t have.',
      'A coach had rated a player. The player\'s own record had changed.',
      'I sat with that for a moment.',
      'In the code it looked reasonable. One player, one set of ratings, one place to store them. Clean. Simple. Wrong.',
      'I knew why it was wrong before I could explain it technically. Twenty years of coaching told me. You never show a player a number without a conversation. A rating without context doesn\'t inform — it wounds. A player who sees a 2 out of 5 on their own screen, alone, with no coach present to explain what was seen and what it means, doesn\'t get feedback. They get a verdict.',
      'The fix wasn\'t complicated. The thinking behind the fix took longer.',
      'What I ended up with is something I won\'t describe in detail. What I\'ll say is this: the coach can see everything. The player sees only what the coach decides to share — in person, in a conversation, on the coach\'s terms. The system doesn\'t make that decision. The coach does.',
      'The data still flows. The agent still uses it. The player still gets better coaching because of it.',
      'They just never see the number.',
      'I had built for the coach and the player. I had forgotten there was a third person watching.',
    ],
  },
  {
    id: 'coachiq-08',
    series: 'CoachIQ',
    seriesColor: 'var(--color-accent)',
    title: 'The Person I Forgot',
    date: '2026-06-25',
    published: false,
    excerpt: 'It was a late evening, somewhere in the middle of a testing session.',
    content: [
      'It was a late evening, somewhere in the middle of a testing session.',
      'I was going through the app as a player — logging a drill, talking to the agent, checking that everything landed correctly in the database. Nothing unusual. The kind of session that is more audit than discovery.',
      'Then I stopped.',
      'I had been thinking about the player. About the coach. About the relationship between them, and how the system served both. And somewhere in that quiet moment I thought about who drives the player to practice. Who waits in the car. Who asks on the way home how it went and gets a one-word answer.',
      'I opened the app as that person.',
      'There was nothing there for them.',
      'What followed was several sessions of building I hadn\'t planned. Not a feature. A different relationship with the same system — one that required its own rules, its own boundaries, its own version of what the agent could and couldn\'t say.',
      'I won\'t describe the architecture. What I\'ll describe is the test.',
      'When it was done, I typed one question into the app as a parent.',
      '"Is my son improving?"',
      'The agent answered. Not with a number. Not with a raw log. With something that sounded like what a coach says after practice when a parent catches them in the hallway and asks directly — specific, honest, and calibrated to someone who loves the player but isn\'t the one coaching them.',
      'I read it twice.',
      'Then I closed the laptop and went to sleep.',
      'I\'m still not sure the parents who need this know it exists. That\'s not a technical problem.',
      'It\'s the one I\'m working on now.',
    ],
  },
];
